import dev.pandasystems.easymodding.extensions.EasyModdingExtension
import dev.pandasystems.easymodding.tasks.GenerateNeoForgeModsTomlTask
import org.gradle.api.internal.project.DefaultProject
import org.gradle.internal.extensions.core.extra
import org.gradle.kotlin.dsl.getByName
import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.io.TempDir
import java.io.File
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class NeoForgeTest {
	@Test
	fun testTask(@TempDir projectDir: File) {
		val project = ProjectBuilder
			.builder()
			.withProjectDir(projectDir)
			.build()

		project.extra["easy_modding.platform"] = "moddev"
		project.repositories.mavenCentral()
		project.plugins.apply("dev.pandasystems.easymodding")

		project.extensions.getByType(EasyModdingExtension::class.java).apply {
			minecraftVersion.set("1.21")
			val resourceUrl = this::class.java.classLoader.getResource("easymodding.mod.json")
				?: throw IllegalArgumentException("Resource not found")
			configPath.set(File(resourceUrl.toURI()))

			neoForge {
				neoForgeVersion.set("21.0.167")
			}
		}

		(project as DefaultProject).evaluate()

		// `generateNeoForgeResources` is a lifecycle task with no action of its own; the actual
		// `neoforge.mods.toml` is written by the `generateNeoForgeModsToml` leaf task it depends on.
		val task = project.tasks.getByName<GenerateNeoForgeModsTomlTask>("generateNeoForgeModsToml")

		// Gradle pre-creates a task's `@OutputDirectory` paths before executing it for real
		// (unlike calling `task.run()` directly), so replicate that here.
		task.outputDir.get().asFile.mkdirs()
		task.run()

		// The unified `dependencies` declared in easymodding.mod.json should have been translated
		// 1:1 into `neoforge.mods.toml`'s `[[dependencies]]` entries.
		val generated = task.outputDir.get().asFile.resolve("META-INF/neoforge.mods.toml").readText()
		assertTrue(generated.contains("required-mod"), "expected required-mod dependency")
		assertTrue(generated.contains("optional-mod"), "expected optional-mod dependency")
		assertTrue(generated.contains("incompatible-mod"), "expected incompatible-mod dependency")
		assertTrue(generated.contains("\"optional\""), "expected optional dependency type")
		assertTrue(generated.contains("\"incompatible\""), "expected incompatible dependency type")

		// pack.mcmeta is generated separately by GeneratePackMcmetaTask (see PackMcmetaTest), not
		// duplicated here, so that enabling multiple loaders doesn't produce clashing
		// `processResources` destination paths.
		assertFalse(
			task.outputDir.get().asFile.resolve("META-INF/pack.mcmeta").exists(),
			"pack.mcmeta should not be generated by generateNeoForgeModsToml"
		)
	}
}
