package dev.pandasystems.easymodding

import dev.pandasystems.easymodding.extensions.EasyModdingExtension
import dev.pandasystems.easymodding.tasks.GenerateFabricModJsonTask
import dev.pandasystems.easymodding.tasks.GenerateForgeModsTomlTask
import dev.pandasystems.easymodding.tasks.GenerateNeoForgeModsTomlTask
import dev.pandasystems.easymodding.tasks.GeneratePackMcmetaTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.language.jvm.tasks.ProcessResources

/**
 * The primary EasyModding Gradle plugin (`dev.pandasystems.easymodding`).
 *
 * This plugin is the single entry point for a multiloader Minecraft mod project. It acts as a thin
 * orchestrator that:
 *
 *  1. Registers the [EasyModdingExtension] (`easyModding { }`) DSL used to configure the mod.
 *  2. Reads the `easy_modding.platform` Gradle property to decide which loader-specific sub-plugin
 *     to apply (`loom` for auto-detecting Fabric Loom variant, `loom-noremap` or `loom-remap` for
 *     explicit Loom variants, `moddev` for NeoForged ModDev, or `forgegradle` for legacy Forge).
 *     This lets a single set of build scripts target different platforms simply by switching the
 *     property.
 *  3. Registers the resource-generation tasks that translate the unified `easymodding.mod.json`
 *     config into the loader-native metadata files, and wires them into `processResources` so they
 *     run automatically as part of a normal build.
 *
 * The actual loader integration (applying Loom/ModDev, resolving Minecraft/NeoForge versions) is
 * delegated to the platform sub-plugins in the `platform` package.
 *
 * ## Task graph
 *
 * Each metadata file is generated by its own single-purpose leaf task, and each loader gets a
 * `generate<Loader>Resources` lifecycle task (no action of its own) that depends on the leaf
 * task(s) that make up that loader's metadata:
 *
 * ```
 * generateFabricResources     -> generateFabricModJson
 * generateNeoForgeResources   -> generateNeoForgeModsToml, generatePackResources
 * generateForgeResources      -> generateForgeModsToml,    generatePackResources
 * ```
 *
 * `pack.mcmeta` is generated by its own [GeneratePackMcmetaTask], shared by NeoForge and Forge
 * (it means the same thing on both), but *not* depended on by Fabric, which has no use for it.
 */
class EasyModdingPlugin : Plugin<Project> {
	override fun apply(target: Project) {
		// Register the `easyModding { }` configuration DSL on the project.
		val easyModdingExtension = target.extensions.create("easyModding", EasyModdingExtension::class.java)

		// The selected build platform, provided by the consumer (e.g. in gradle.properties as
		// `easy_modding.platform=loom`). May be null when the project is not building for a
		// specific loader (for example a shared "common" subproject).
		val platform = target.findProperty("easy_modding.platform") as? String

		// Every EasyModding project is a Java project and benefits from IDEA integration.
		target.pluginManager.apply("java")
		target.pluginManager.apply("idea")

		// Apply the loader-specific sub-plugin based on the selected platform.
		when (platform) {
			"loom" -> target.pluginManager.apply("dev.pandasystems.easymodding.loom")
			"loom-noremap" -> target.pluginManager.apply("dev.pandasystems.easymodding.loom-noremap")
			"loom-remap" -> target.pluginManager.apply("dev.pandasystems.easymodding.loom-remap")
			"moddev" -> target.pluginManager.apply("dev.pandasystems.easymodding.moddev")
			"forgegradle" -> target.pluginManager.apply("dev.pandasystems.easymodding.forgegradle")
			null -> {} // No platform selected: skip loader wiring (e.g. a common/shared module).
			else -> throw IllegalArgumentException(
				"Unknown platform: $platform (Available: loom, loom-noremap, loom-remap, moddev, forgegradle)"
			)
		}

		// Leaf task that generates `fabric.mod.json`. Only runs when the Fabric loader is
		// enabled via the `easyModding { fabric() }` DSL.
		val generateFabricModJson =
			target.tasks.register("generateFabricModJson", GenerateFabricModJsonTask::class.java) {
				configFile.convention(easyModdingExtension.configPath)
				outputDir.convention(target.layout.buildDirectory.dir("generated/easy-modding/fabric/resources"))
				onlyIf { easyModdingExtension.fabric.enabled.getOrElse(false) }
			}

		// Leaf task that generates NeoForge's `META-INF/neoforge.mods.toml`. Only runs when the
		// NeoForge loader is enabled via the `easyModding { neoForge() }` DSL.
		val generateNeoForgeModsToml =
			target.tasks.register("generateNeoForgeModsToml", GenerateNeoForgeModsTomlTask::class.java) {
				configFile.convention(easyModdingExtension.configPath)
				outputDir.convention(target.layout.buildDirectory.dir("generated/easy-modding/neoforge/resources"))
				onlyIf { easyModdingExtension.neoForge.enabled.getOrElse(false) }
			}

		// Leaf task that generates legacy Forge's `META-INF/mods.toml`. Only runs when the Forge
		// loader is enabled via the `easyModding { forge() }` DSL.
		val generateForgeModsToml =
			target.tasks.register("generateForgeModsToml", GenerateForgeModsTomlTask::class.java) {
				configFile.convention(easyModdingExtension.configPath)
				outputDir.convention(target.layout.buildDirectory.dir("generated/easy-modding/forge/resources"))
				onlyIf { easyModdingExtension.forge.enabled.getOrElse(false) }
			}

		// Leaf task that generates the shared `pack.mcmeta`, understood identically by NeoForge
		// and Forge. Generated exactly once (rather than once per enabled loader) so that
		// enabling more than one loader at a time (e.g. in a shared/common module) doesn't make
		// `processResources` see the same `pack.mcmeta` destination path contributed more than
		// once, which would fail the build with a duplicate-entry error. Runs whenever NeoForge or
		// Forge is enabled; Fabric has no use for `pack.mcmeta`, so it doesn't trigger this task.
		val generatePackResources =
			target.tasks.register("generatePackResources", GeneratePackMcmetaTask::class.java) {
				configFile.convention(easyModdingExtension.configPath)
				outputDir.convention(target.layout.buildDirectory.dir("generated/easy-modding/pack/resources"))
				onlyIf {
					easyModdingExtension.neoForge.enabled.getOrElse(false) ||
						easyModdingExtension.forge.enabled.getOrElse(false)
				}
			}

		// Per-loader lifecycle tasks with no action of their own: they simply group together the
		// leaf task(s) that make up that loader's metadata, so `./gradlew generate<Loader>Resources`
		// generates everything that loader needs in one go. `pack.mcmeta` is only relevant to
		// NeoForge/Forge, so only those two depend on `generatePackResources`; Fabric does not.
		val generateFabricResources = target.tasks.register("generateFabricResources") {
			group = "easymodding"
			description = "Generates every Fabric metadata file (fabric.mod.json)."
			dependsOn(generateFabricModJson)
		}
		val generateNeoForgeResources = target.tasks.register("generateNeoForgeResources") {
			group = "easymodding"
			description = "Generates every NeoForge metadata file (neoforge.mods.toml, pack.mcmeta)."
			dependsOn(generateNeoForgeModsToml, generatePackResources)
		}
		val generateForgeResources = target.tasks.register("generateForgeResources") {
			group = "easymodding"
			description = "Generates every Forge metadata file (mods.toml, pack.mcmeta)."
			dependsOn(generateForgeModsToml, generatePackResources)
		}

		// Feed the generated metadata into the standard resource-processing pipeline so the files
		// end up on the mod's classpath / inside the built jar automatically. `from(...)` is wired
		// to the leaf tasks directly (rather than the lifecycle tasks above, which have no outputs
		// of their own) so `processResources` picks up their actual generated files, while still
		// depending on the lifecycle tasks to keep `./gradlew generate<Loader>Resources` working
		// as a complete, standalone command.
		target.tasks.named("processResources", ProcessResources::class.java) {
			dependsOn(generateFabricResources, generateNeoForgeResources, generateForgeResources)
			from(generateFabricModJson)
			from(generateNeoForgeModsToml)
			from(generateForgeModsToml)
			from(generatePackResources)
		}
	}
}
